apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: nodejs-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      automountServiceAccountToken: true
      containers:
      - image:  496212753419.dkr.ecr.eu-central-1.amazonaws.com/nodejs-app:latest # pushed there by GitHub Actions
        imagePullPolicy: Always
        name: nodejs-app-container
        ports:
        - containerPort: 3000
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  namespace: nodejs-ns
spec:
  ports:
  - nodePort: 30201
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs-app
  type: NodePort

---

